import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"; // Standard import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bPath = process.env.NODE_ENV === 'production' ? '/lava_landing_page_nextjs' : '';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    ><head>
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet" />

        <link rel="stylesheet" type="text/css" href={`${bPath}/assets/css/bootstrap.min.css`} precedence="default" />
        <link rel="stylesheet" type="text/css" href={`${bPath}/assets/css/font-awesome.css`} precedence="default" />
        <link rel="stylesheet" href={`${bPath}/assets/css/templatemo-lava.css`} precedence="default" />
        <link rel="stylesheet" href={`${bPath}/assets/css/owl-carousel.css`} precedence="default" />
      </head><body className="min-h-full flex flex-col">{children}
        {/* 1. Load jQuery first */}
        <Script src={`${bPath}/assets/js/jquery-2.1.0.min.js`} strategy="beforeInteractive" />

        {/* 2. Load Bootstrap dependencies */}
        <Script src={`${bPath}/assets/js/popper.js`} strategy="beforeInteractive" />
        <Script src={`${bPath}/assets/js/bootstrap.min.js`} strategy="beforeInteractive" />

        {/* 3. Load Plugins */}
        <Script src={`${bPath}/assets/js/owl-carousel.js`} strategy="afterInteractive" />
        <Script src={`${bPath}/assets/js/scrollreveal.min.js`} strategy="afterInteractive" />
        <Script src={`${bPath}/assets/js/waypoints.min.js`} strategy="afterInteractive" />
        <Script src={`${bPath}/assets/js/jquery.counterup.min.js`} strategy="afterInteractive" />
        <Script src={`${bPath}/assets/js/imgfix.min.js`} strategy="afterInteractive" />

        {/* 4. Global Init (Runs last) */}
        <Script src={`${bPath}/assets/js/custom.js`} strategy="afterInteractive" />
      </body></html>
  );
}
